### ISSUE TITLE
Starting a new search should clear previous results

### ISSUE THREAD

**Issue by ExtReMLapin** [hexarobi/stand-lua-constructor#22]
Starting a new search should clear previous results (attachments, and probably everywhere else it's used)

**Comment by hexarobi** [comment]
Is this still an issue? I think this has been fixed already, but if not please provide more detailed instructions, doing an attachment search does clear previous results for me. Thanks for the bug report! =)

**Comment by ExtReMLapin** [comment]
yep perfect, thanks, (sorry for the delayed answer)
