### ISSUE TITLE
"Install Curated Constructs" button is created everytime the list is entered

### ISSUE THREAD

**Issue by Sainan** [hexarobi/stand-lua-constructor#53]
![image](https://github.com/hexarobi/stand-lua-constructor/assets/63328889/10d4a604-8bc0-477d-bf4f-2ee0bc04a783)

**Comment by hexarobi** [comment]
Sorry I missed this bug report somehow. But I think I fixed this already a while back now, please let me know if you see it again. Thank you for the report! =)
